// COMMON
export const START_SPINNER = "START_SPINNER";
export const SET_CURRENT = "SET_CURRENT";

// AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const USERS_LOADED = "USERS_LOADED";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USERS = "GET_USERS";
export const FILTERED_USERS = "FILTERED_USERS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

// TRANSACTION
export const GET_TRANSACTION = "GET_TRANSACTION";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const USER_TRANSACTIONS = "USER_TRANSACTIONS";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const FILTERED_TRANSACTION = "FILTERED_TRANSACTION";
export const SEARCH_TRANSACTION = "SEARCH_TRANSACTION";
export const TRANSACTION = "TRANSACTION";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";

// CUSTOMER
export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CUSTOMER_ERROR = "CUSTOMER_ERRO";

// PRODUCT
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERRO";